apiVersion: v1
kind: PersistentVolume
metadata:
  name: database-files
spec:
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  azureFile:
    shareName: pumpkinpatchdata_1629654668287
    secretName:  azure-secret
    readOnly: false

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: wordpress-files
spec:
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  azureFile:
    shareName: pumpkinpatchdata_1629654668287
    secretName:  azure-secret
    readOnly: false

