---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: database-files
spec:
  resources:
    requests:
      storage: 2Gi
  accessModes:
    - ReadWriteOnce


---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wordpress-files
spec:
  resources:
    requests:
      storage: 2Gi
  accessModes:
    - ReadWriteOnce

